# Generated by Django 4.0.3 on 2022-03-08 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='none', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='none', max_length=50)),
                ('wildlife', models.CharField(default='none', max_length=100)),
                ('about', models.CharField(default='none', max_length=150)),
                ('visitors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='traversetnapi.member')),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('fish', models.CharField(max_length=50)),
                ('animals', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('flowchart', models.CharField(max_length=50)),
                ('visitors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rivers', to='traversetnapi.member')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('memberId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='traversetnapi.member')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traversetnapi.place', verbose_name='Place')),
                ('river', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traversetnapi.river', verbose_name='River')),
            ],
        ),
    ]
