# Generated by Django 4.0.3 on 2022-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traversetnapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
