# Generated by Django 4.0.3 on 2022-03-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traversetnapi', '0002_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='traversetnapi.member')),
                ('placeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traversetnapi.place', verbose_name='Place')),
                ('riverId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traversetnapi.river', verbose_name='River')),
            ],
        ),
    ]
