# Generated by Django 4.0.3 on 2022-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traversetnapi', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.CharField(max_length=150),
        ),
    ]
