# Generated by Django 4.0.3 on 2022-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traversetnapi', '0006_rename_memberid_trip_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='visitors',
        ),
        migrations.AddField(
            model_name='river',
            name='visitors',
            field=models.ManyToManyField(related_name='rivers', to='traversetnapi.member'),
        ),
    ]
