# Generated by Django 4.0.3 on 2022-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traversetnapi', '0007_remove_river_visitors_river_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='visitors',
        ),
        migrations.AddField(
            model_name='place',
            name='visitors',
            field=models.ManyToManyField(related_name='places', to='traversetnapi.member'),
        ),
    ]
